### ISSUE TITLE
setup.py fails on mac

### ISSUE THREAD

**Issue by rameshraithatha** [flipkart-incubator/Astra#11]
While running setup.py on my mac it asks me to run it with sudo for the `pip install` but later while running the `brew install` command it fails since brew doesn't like sudo.

I would suggest moving the installation of external dependencies to the user and you should concentrate on installing the python dependencies only.

Also, setting up the tool is little painful right now. Installing the tool should be as simple as running a `pip install astra` or `apt-get install astra` command. Running the tool should be as simple as running a command `astra`.

**Comment by sunitavc** [comment]
Workaround: pip install -r requirements.txt
This just works provided we have pip installed etc.

**Comment by sagarpo** [comment]
@sunitavc Yes, that will work.

**Comment by sagarpo** [comment]
@rameshraithatha You can now directly use sudo pip install -r requirements.txt for set up.
