### ISSUE TITLE
    print "Failed to update DB"

### ISSUE THREAD

**Issue by balagpy** [flipkart-incubator/Astra#114]
Hi Team,

I am facing the following issue.

File "api.py", line 95
    print "Failed to update DB"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to update DB")?

**Comment by Niba-nazar** [comment]
Hi,


I am also facing the same issue, Please assist 

```
root@niba:~/Astra# python3.9 astra.py --help
  File "/root/Astra/astra.py", line 46
    print"[-]Failed to Parse collection"
         ^
SyntaxError: invalid syntax
root@niba:~/Astra# cd API/
root@niba:~/Astra/API# python api.py
  File "api.py", line 95
    print"Failed to update DB"
         ^
SyntaxError: invalid syntax

```

**Comment by S-Surya** [comment]
Closing the issue since this is fixed with Python 3 migration
