### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by shaputta** [flipkart-incubator/Astra#116]
Hi, I am trying to run astra post all requirements pulled. But, getting the following error.
![image](https://user-images.githubusercontent.com/60346998/124419062-70042300-dd7a-11eb-9d59-ba2ad83233b9.png)
 
Can you please look into it and resolve.

Thanks in Advance.

**Comment by pvital** [comment]
The `requests` is one of the required modules, and it's listed in the `requirements.txt` file. 

I suggest you follow the last step of the [installation](https://github.com/flipkart-incubator/Astra#installation) process and try again.
