### ISSUE TITLE
Doesnt get report

### ISSUE THREAD

**Issue by swankmotor** [flipkart-incubator/Astra#25]
Hello. What i do wrong?
http://prntscr.com/j4s5f6

**Comment by swankmotor** [comment]
[http://prntscr.com/j4sdit](url)

**Comment by sagarpo** [comment]
@swankmotor. Did you scan it through the web interface? was your mongoDB running when you started the scan?

**Comment by sagarpo** [comment]
@swankmotor Please check this document for more information  : https://www.astra-security.info/installation/
