### ISSUE TITLE
Unable to launch Astra

### ISSUE THREAD

**Issue by rakeshkmr516** [flipkart-incubator/Astra#27]
@sagarpo Performed steps and could you please let me know if am missing any information to launch astra CLI/ GUI mode
$ git clone https://github.com/flipkart-incubator/Astra

$ cd Astra

$ pip install -r requirements.txt ( Navigated to pip folder using windows OS)

I have installed below versions of Python and MongoDB
Python: 3.6.4
MongoDB shell version v3.6.4
I have run mongodb commands mongod and mongo on different command line terminals
Cloned and navigated to astra folder and executed below returns me errors
`G:\astra\Astra\API>cd ..

G:\astra\Astra>python astra.py
  File "astra.py", line 36
    print "[-]Failed to Parse collection"
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "
-]Failed to Parse collection")?

G:\astra\Astra>`

`
G:\astra\Astra\API>python api.py
  File "api.py", line 58
    print "Failed to update DB"
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "F
ailed to update DB")?`

**Comment by sagarpo** [comment]
@rakeshkmr516 .. currently it doesn't support in windows. Try it on linux or in mac.

**Comment by elcreek** [comment]
i think the solution is using python2.7
