### ISSUE TITLE
getting error while using web based

### ISSUE THREAD

**Issue by unmesh92** [flipkart-incubator/Astra#28]
root@kali:~/Astra/API# python api.py 
Failed to connect to MongoDB.
root@kali:~/Astra/API#

**Comment by unmesh92** [comment]
root@kali:~/Astra/API# python api.py 
Failed to connect to MongoDB.
root@kali:~/Astra/API#

**Comment by unmesh92** [comment]
Failed to connect to MongoDB.
 getting above error

**Comment by alimukarramm** [comment]
Hello, I am having same error Failed to connect to mongodb. I did install the mongodo in my kali but also not able to access your site https://www.astra-security.info/installation/. please help. thanks.

**Comment by ledgefarmdoc** [comment]
Hi,
getting Import error when I am run below command

root@kali:~/Astra# python astra.pyc
Traceback (most recent call last):
  File "/root/Astra/astra.py", line 38, in <module>
    from API.api import main
  File "/root/Astra/API/api.py", line 38, in <module>
    from astra import *
  File "/root/Astra/astra.py", line 38, in <module>
    from API.api import main
ImportError: cannot import name main
