### ISSUE TITLE
Testing GET request returns error

### ISSUE THREAD

**Issue by sugarjig** [flipkart-incubator/Astra#51]
I'm trying to follow the instructions to get started, but I'm not getting very far. I have pulled the Mongo image and built the CLI Docker image. I'm running the service I want to test locally, and now I'm trying to run the following command, replacing `<token`> with a valid token I obtain ahead of time:
```sh
docker run --rm -it --link astra-mongo:mongo astra-cli -u http://docker.for.mac.localhost:8080/v1/users/me --headers '{"Authorization": "Bearer <token>"}'
```
I get the following stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./astra.py", line 121, in modules_scan
    sqli_check(url,method,headers,body,scanid)
  File "/app/modules/sqli.py", line 116, in sqli_check
    set_option_status = set_options_list(url,method,headers,body,taskid)
  File "/app/modules/sqli.py", line 34, in set_options_list
    if options_list.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

I've also tried the same call in the Astra GUI, but I get "Broken Authentication and session management" and the API returning a 401. It's almost as if Astra is not properly sending the Authorization header.

Is there something I'm missing from the command? Am I supposed to pass the command a valid token?

**Comment by sagarpo** [comment]
@sugarjig.  How are you passing Authorization header? It should be in proper JSON format 
Example: {"Auth-header": "Auth-header-value"}

**Comment by sugarjig** [comment]
AFAIK, I'm passing the header correctly. The command I'm executing has `--headers '{"Authorization": "Bearer <token>"}'`

**Comment by sagarpo** [comment]
@sugarjig Have you tried the same through the web interface? Are you getting the same error for web interface as well?

**Comment by sugarjig** [comment]
Yes, I have tried it through the GUI. The error I get there is "Broken Authentication and session management" with a payload from our service that matches that expected when the token is incorrect or missing.

**Comment by sagarpo** [comment]
@sugarjig I will look into this. Give me some time.

**Comment by YUNUS0407** [comment]
helo evreone

**Comment by YUNUS0407** [comment]
my comit
