### ISSUE TITLE
Getting error "Failed to test Broken authentication and session management"

### ISSUE THREAD

**Issue by BilalK-Continuum** [flipkart-incubator/Astra#54]
While scanning any API getting below message ;

/usr/local/lib/python2.7/dist-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only a                         fter forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
Failed to test Broken authentication and session management

**Comment by sagarpo** [comment]
@BilalK-Continuum "Failed to test Broken authentication and session management" you can ignore error since it's testing properly but not showing a proper message.  Also for mongo error, it's warning so you can ignore it or else you can start mongo like this to avoid warning: 
```$ sudo mongod --fork --logpath=output.log```
