### ISSUE TITLE
API Status - Status of the API is in In Progress for more than 2 days

### ISSUE THREAD

**Issue by ArjunReddyD** [flipkart-incubator/Astra#62]
3 Issues found in the scan, but Status still showing as In Progress. How do I know that Scanning is completed or not?
1. CORS Misconfiguration
2. Broken Authentication and session management
3. Cross Site Scripting

**Comment by sagarpo** [comment]
@ArjunReddyD  Did you check that?

**Comment by ArjunReddyD** [comment]
@sagarpo Sorry for not responding these days, I was remote. I am using Astra in GUI-Docker mode and inside Logs folder, Scan.log file is empty. No logs found in it.
![image](https://user-images.githubusercontent.com/29158737/46516465-85755700-c887-11e8-81ea-5370bdcf2684.png)

**Comment by sagarpo** [comment]
@ArjunReddyD  Can you share /app/logs/scan.log? This file will be present inside the docker directory.

**Comment by ArjunReddyD** [comment]
Sorry I didn't explore it again. @sagarpo I will close this for now and in future if I come across i will reopen it
