### ISSUE TITLE
Local copy of JS and CSS

### ISSUE THREAD

**Issue by zhuzhibin123** [flipkart-incubator/Astra#68]
Step 6/10 : RUN pip install -r requirements.txt
 ---> Running in 52fe9a9b747f

Collecting requests (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a45703350>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/requests/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a45703650>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/requests/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a45703810>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/requests/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a45703950>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/requests/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a45703a90>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/requests/
  Could not find a version that satisfies the requirement requests (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for requests (from -r requirements.txt (line 1))
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by zhuzhibin123** [comment]
Thank you for your reply. The country has been resolved, but a new problem has been encountered. When executing the command Python api. py, Failed to connect to MongoDB. MongoDB is running

**Comment by sagarpo** [comment]
@zhuzhibin123 You need to run mongo container as well.
```
$ docker pull mongo
$ docker run --name astra-mongo -d mong
```

**Comment by zhuzhibin123** [comment]
The input command shows that it is already running, but the running Python api.py command indicates that the connection failed.

$ docker run --name astra-mongo -d mongo
/usr/bin/docker-current: Error response from daemon: Conflict. The container name "/astra-mongo" is already in use by container 64befbf1d377995730806c3176c4631a3638cdc0c1fdbb0be2af7dcd5ba8796d. You have to remove (or rename) that container to be able to reuse that name..
See '/usr/bin/docker-current run --help'.
$ docker ps 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
18c2a56c8bfc        astra               "python ./api.py '..."   28 hours ago        Up 28 hours         0.0.0.0:8094->8094/tcp   goofy_joliot
64befbf1d377        mongo               "docker-entrypoint..."   2 days ago          Up 2 days           27017/tcp                astra-mongo

**Comment by zhuzhibin123** [comment]
It has not been solved yet.

**Comment by mohangcsm** [comment]
@zhuzhibin123 
it seems ur Mongo container is already created. Please use the below command to see if it is already created.

docker ps -a

please use below command to start it manually.

docker start 64befbf1d377

Once it is started, please follow the instructions mentioned in readme file to start Astra docker either in cli or gui mode.

**Comment by zhuzhibin123** [comment]
When I executed the order, there was another problem.
$python api.py 
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
 RequestsDependencyWarning)
Failed to connect to MongoDB.

**Comment by zhuzhibin123** [comment]
When I click on Submit to display the status, is there a problem {status":"a2598d4610331c8187b73b76e411dc8"}?

**Comment by zhuzhibin123** [comment]
When I submitted, there was a hint in the window. Is there any problem?{status“：”a2598d4610331c8187b73b76e411dc8“}

**Comment by sagarpo** [comment]
@zhuzhibin123 That means scan has started and worked fine.

**Comment by zhuzhibin123** [comment]
Hi，
Why didn't I see the progress? How long will it take to see the report?

**Comment by sagarpo** [comment]
@zhuzhibin123 It will only show "in progress" or "completed" and it takes 5 minutes max to complete single API scan.

**Comment by zhuzhibin123** [comment]
Hi，
When I submitted, there was a hint in the window，{status“：”a2598d4610331c8187b73b76e411dc8“}，Is it normal? Or is there a problem?

**Comment by sagarpo** [comment]
@zhuzhibin123 Yes that's standard behave. The scan has been started already.

**Comment by zhuzhibin123** [comment]
![default](https://user-images.githubusercontent.com/44351312/48399592-0cf39700-e75f-11e8-91e3-4b8a49fc3f34.PNG)

**Comment by zhuzhibin123** [comment]
Hi，@sagarpo 
Submitted, it seems that there is no state to see screenshots.

**Comment by sagarpo** [comment]
@zhuzhibin123 Do you have internet connection on the box where you hosted the Astra? Astra requires external JS and CSS to load from the internet.

**Comment by zhuzhibin123** [comment]
Hi，@sagarpo
We are private networks, can not directly connect to the Internet, the external JS and CSS download address?

**Comment by sagarpo** [comment]
@zhuzhibin123 it loads from bootstrapcdn.com.

**Comment by zhuzhibin123** [comment]
Hi，
@sagarpo 
Which directory should JS documents be placed in?

**Comment by sagarpo** [comment]
@zhuzhibin123 I will do required changes and will push it in a couple of days.

**Comment by zhuzhibin123** [comment]
@sagarpo OK, we are looking forward to it.

**Comment by sagarpo** [comment]
@zhuzhibin123 This is fixed. You can clone again and try the same.

**Comment by zhuzhibin123** [comment]
okay
