### ISSUE TITLE
Webscans keep crashing on Mac 

### ISSUE THREAD

**Issue by madheshr** [flipkart-incubator/Astra#73]
Hi
  A simple webscan keeps crashing.  Here is the trace.  Is there a specific version of python i should be using?

Process:               Python [35505]
Path:                  /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.15 (2.7.15)
Code Type:             X86-64 (Native)
Parent Process:        Python [34775]
Responsible:           Python [35505]
User ID:               522130245

Date/Time:             2018-11-20 20:23:57.333 -0800
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        0DB45F5A-C18B-C0F5-5D43-DFB6BEDCBC7B

Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace OBJC, Code 0x1

Application Specific Information:
crashed on child side of fork pre-exec
objc[35505]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.

**Comment by prajal** [comment]
This is apparently due to some new security changes made in High Sierra that are breaking lots of Python things that use fork(). Please refer below links
https://github.com/jhaals/ansible-vault/issues/60
https://github.com/ansible/ansible/issues/32499
