### ISSUE TITLE
how to use the web based interface

### ISSUE THREAD

**Issue by Jennifer0099** [flipkart-incubator/Astra#84]
Hello, can I use this software to test the facebook APIs and how can I do that. From the screenshot, I see the URL is http://localhost/checkout.php, so do I need to use the API that I want to test to connect to the localhost website through a software like POSTMAN? Because I am just a beginner with APIs, so I don't know how to use this testing software.

**Comment by sagarpo** [comment]
@Jennifer0099 You can check this video: https://www.youtube.com/watch?v=EXAO-187ygI.  Hope this will help.

**Comment by Jennifer0099** [comment]
Thanks so much! This is helpful and now I know the localhost is not a must, but I still don't know how can I get the information like URL, Header, and Bodies.

**Comment by sagarpo** [comment]
@Jennifer0099  What's the use case here?

**Comment by Jennifer0099** [comment]
I am doing a project based your code, and I want to test whether the software can realize the functions it claims and how well it can perform that. And maybe I also need to know how this software can do that. I read something about RESTful API, so I have a rough idea of this area now, but just some theoretical staff. And now I want to find some opensource APIs to test, like Twitter and Facebook.

**Comment by sagarpo** [comment]
If you want to scan for security vulnerabilities, you need to have valid URL, headers and body.  That you can find out developer docs for Facebook!

**Comment by Jennifer0099** [comment]
Thanks, so I need to understand the endpoints of the APIs then I can know how to get the valid URL, headers and body, right?
![image](https://user-images.githubusercontent.com/45819053/49869385-8b9c2c80-fe10-11e8-9c6e-3dfa6e47c0df.png)

**Comment by sagarpo** [comment]
Yes
