### ISSUE TITLE
getting exception

### ISSUE THREAD

**Issue by ilayathalapathy-3719** [flipkart-incubator/Astra#85]
![astra error](https://user-images.githubusercontent.com/25341791/50084866-651a2f00-021e-11e9-9932-50a231363b1c.JPG)
Getting exception error while running astra.py file and 
![api py error](https://user-images.githubusercontent.com/25341791/50085022-d528b500-021e-11e9-8775-5e67753ff272.JPG)

Getting exception error while running API/api.py file.

Final scan result is blank

**Comment by sagarpo** [comment]
@avi3719 Can you try to scan the same from web UI?

**Comment by balzer82** [comment]
Same from WebUI:

```
docker run --rm -it --link astra-mongo:mongo -p 8094:8094 astra
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
/usr/local/lib/python2.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
exception in XSS
exception in Open redirect
exception in XXE
exception in CRLF
exception in security_headers
```

**Comment by balzer82** [comment]
I made it with a Mongo in Docker and the `python astra.py` and now it works. Wrote it down [here](https://mechlab-engineering.de/2019/01/security-testing-and-deployment-of-an-api-release-your-flask-app-to-the-internet/).

**Comment by sagarpo** [comment]
@balzer82 @avi3719 Did you start mongo server? You need to run mongo server first as mentioned in README.

**Comment by sagarpo** [comment]
@balzer82 Thanks.
