### ISSUE TITLE
{"status":"Failed"}

### ISSUE THREAD

**Issue by Jennifer0099** [flipkart-incubator/Astra#86]
I just copied the URL, headers (without any body information) from POSTMAN, and it is in JSON format, but I get {"status":"Failed"}. Why does this happen?

**Comment by Jennifer0099** [comment]
I changed the format of the header to XML, and now the status changed to {"status":"a686fbf79f7ae22d2fcfe4d76f27910a"}

**Comment by Jennifer0099** [comment]
the header is like ----- OAuth oauth_consumer_key="W8rvRGIPauNLgmNBmEtGqqxG",oauth_token="1026851944051163137-XASS7kzON1WhDLK5PJSQGmsV3DmUu",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1547560314",oauth_nonce="x3UGfxcgLef",oauth_version="1.0",oauth_signature="r74zJx1xlPPobUvy7UjLoDc4Hdc%3D"

**Comment by Jennifer0099** [comment]
the URL is like https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=Jennife1625299

**Comment by Jennifer0099** [comment]
![image](https://user-images.githubusercontent.com/45819053/51187691-a6b0ff00-18dc-11e9-83a8-184a61e05f4d.png)

**Comment by Jennifer0099** [comment]
I find I have already got some information, but nothing useful.

**Comment by sagarpo** [comment]
@Jennifer0099 Can you share the exact header you tried?

**Comment by Jennifer0099** [comment]
the second time i changed like --- "Consumer Key" : "W8rvRGIPauNLgmNBmEtgGqqx",  in JSON format, then I got {"status":"a686fbf79f7ae22d2fcfe4d76f27910a"}

**Comment by Jennifer0099** [comment]
it showed completed but I don't get any report

**Comment by Jennifer0099** [comment]
and do I must give some information in body? can I leave it be empty

**Comment by sagarpo** [comment]
@Jennifer0099 That means the URL doesn't have any security vulnerabilities.
